[program:chromedriver]
command=/usr/local/bin/chromedriver --port=9225 --allowed-ips=127.0.0.1 --log-level=INFO
autostart=false
autorestart=true
startsecs=2
stdout_logfile=/var/log/supervisord/chromedriver
redirect_stderr=true
