#!/usr/bin/env python3
"""Generate policy_registry.go from Chromium policy definition YAML files.

Usage:
    python3 generate_registry.py <chromium-policy-dir>

Where <chromium-policy-dir> is the path to:
    chromium/src/components/policy/resources/templates/policy_definitions/

Example:
    python3 generate_registry.py /home/debianuser/chromium-cache/src/components/policy/resources/templates/policy_definitions
"""

import os
import sys
import yaml

CHROMIUM_TYPE_TO_GO = {
    "main": ("PolicyTypeBool", "bool"),
    "int": ("PolicyTypeInt", "int"),
    "int-enum": ("PolicyTypeInt", "int"),
    "string": ("PolicyTypeString", "string"),
    "string-enum": ("PolicyTypeString", "string"),
    "list": ("PolicyTypeListString", "list"),
    "string-enum-list": ("PolicyTypeListString", "list"),
    "dict": ("PolicyTypeDict", "dict"),
    "external": ("PolicyTypeDict", "dict"),
}


def extract_policies(policy_dir: str) -> dict[str, str]:
    results = {}
    for root, _, files in os.walk(policy_dir):
        for f in files:
            if not f.endswith(".yaml"):
                continue
            path = os.path.join(root, f)
            try:
                with open(path) as fh:
                    data = yaml.safe_load(fh)
            except Exception:
                continue
            if not isinstance(data, dict):
                continue

            supported = data.get("supported_on", [])
            if not isinstance(supported, list):
                continue
            if not any(
                isinstance(s, str)
                and (s.startswith("chrome.*") or s.startswith("chrome.linux"))
                for s in supported
            ):
                continue

            name = data.get("name", f.removesuffix(".yaml"))
            ptype = data.get("type", "")
            mapping = CHROMIUM_TYPE_TO_GO.get(ptype)
            if mapping is None:
                print(f"WARNING: skipping {name}: unknown type {ptype!r}", file=sys.stderr)
                continue

            results[name] = mapping[0]

    return results


def generate_go(policies: dict[str, str]) -> str:
    lines = [
        "// Code generated by generate_registry.py from Chromium policy definitions. DO NOT EDIT.",
        "",
        "package policy",
        "",
        "func init() {",
        "\tpolicyRegistry = map[string]PolicyValueType{",
    ]
    max_name_len = max(len(name) for name in policies) + 2  # +2 for quotes
    for name in sorted(policies.keys()):
        go_const = policies[name]
        key = f'"{name}":'
        lines.append(f"\t\t{key:<{max_name_len + 1}} {go_const},")
    lines.append("\t}")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        sys.exit(1)

    policy_dir = sys.argv[1]
    if not os.path.isdir(policy_dir):
        print(f"ERROR: {policy_dir} is not a directory", file=sys.stderr)
        sys.exit(1)

    policies = extract_policies(policy_dir)
    print(f"Extracted {len(policies)} Linux-supported policies", file=sys.stderr)

    go_code = generate_go(policies)
    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "policy_registry.go")
    with open(out_path, "w") as f:
        f.write(go_code)
    print(f"Wrote {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
